# Generated by Django 2.2.12 on 2020-06-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default='')),
                ('end_date', models.DateTimeField(default='')),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
