# Generated by Django 2.2.12 on 2020-06-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_intern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='end_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='intern',
            name='start_date',
            field=models.DateField(default=''),
        ),
    ]
